
# Complete Pytorch Tensor Tutorial (Initializing Tensors, Math, Indexing, Reshaping)

From [YouTube - Complete Pytorch Tensor Tutorial (Initializing Tensors, Math, Indexing, Reshaping)](https://www.youtube.com/watch?v=x9JiIFvlUwk&list=PLhhyoLH6IjfxeoooqP9rhU3HJIAVAJ3Vz&index=2)

In [1]:
import torch

## Tensor Initialization

In [2]:
# Creating a tensor
device = "cuda" if torch.cuda.is_available() else "cpu"

my_tensor = torch.tensor(
    [[1, 2, 3], [4, 5, 6]], 
    dtype=torch.float32,
    device=device,
    requires_grad=True
    )

print(my_tensor)
print(my_tensor.dtype)
print(my_tensor.device)
print(my_tensor.shape)
print(my_tensor.requires_grad)

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0', requires_grad=True)
torch.float32
cuda:0
torch.Size([2, 3])
True


In [3]:
# Other common initialization methods
empty_x = torch.empty(size = (3, 3))                        # Create a random uninitialized 3x3 tensor
zero_x = torch.zeros((3,3))                                 # Create a 3x3 tensor of 0's
rand_x = torch.rand((3,3))                                  # Uniform random sampling [0,1]
ones_x = torch.ones((3,3))                                  # Create 3x3 matrix of all 1's
eye_x = torch.eye(5,5)                                      # Identity matrix (1's on diagonal, rest 0)
arange_x = torch.arange(start=0, end=5, step=1)             # Increasing values from start to end, increasing by step size
linspace_x = torch.linspace(start=0.1, end=1, steps=10)     # Equally spacesd values from start to end
norm_x = torch.empty(size=(1,5)).normal_(mean = 0, std = 1) # Random points sampled from a normal distribution
uniform_x = torch.empty(size=(1,5)).uniform_(0,1)           # Uniform distribution from 0, 1
diag_x = torch.diag(torch.ones(3))                          # Diagonal matrix with ones on the diagonal

print(empty_x)
print(zero_x)
print(rand_x)
print(ones_x)
print(eye_x)
print(arange_x)
print(linspace_x)
print(norm_x)
print(uniform_x)
print(diag_x)


tensor([[5.1935e+14, 7.0065e-45, 0.0000e+00],
        [0.0000e+00,        nan, 0.0000e+00],
        [1.1578e+27, 0.0000e+00, 4.7545e+30]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[0.0731, 0.0110, 0.9865],
        [0.3018, 0.8180, 0.4971],
        [0.6125, 0.2526, 0.0035]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
tensor([0, 1, 2, 3, 4])
tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])
tensor([[-0.1113, -0.7007, -0.1484,  0.6645,  1.1951]])
tensor([[0.1399, 0.9761, 0.0967, 0.3145, 0.6898]])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [11]:
# How to initialize and convert tensors to other types (int,  float, double)
tensor = torch.arange(4) # default start=0, step=1, dtype=int64
print(tensor.bool())
print(tensor.short())   # int16
print(tensor.long())    # int64
print(tensor.half())    # float16
print(tensor.float())   # float32
print(tensor.double())  # float64 

# Array to Tensor conversion and vice-versa
import numpy as np
np_array = np.zeros((5,5))

# Numpy -> Tensor
tensor = torch.from_numpy(np_array)

# Tensor -> Numpy
np_array_back = tensor.numpy()


tensor([False,  True,  True,  True])
tensor([0, 1, 2, 3], dtype=torch.int16)
tensor([0, 1, 2, 3])
tensor([0., 1., 2., 3.], dtype=torch.float16)
tensor([0., 1., 2., 3.])
tensor([0., 1., 2., 3.], dtype=torch.float64)


---

## Tensor Math Comparison

In [19]:
x = torch.tensor([1,2,3])
y = torch.tensor([9,8,7])

# Addition
# Option 1
z1 = torch.empty(3)
torch.add(x, y, out=z1)

# Option 2
z2 = torch.add(x, y)

# Option 3
z = x + y

# Subtraction
z = x - y

# Division
z = torch.true_divide(x, y) # Element-wise division if they are of equal shape. If y is a scalar, divides all elts of x by y

# Inplace operations
t = torch.zeros(3)
t.add_(x)   # Operations followed by underscore are inplace
t += x      # t = t + x is NOT in place, creates a copy first

# Exponentiation
z = x.pow(2)    # Element-wise exponentiation (1**2, 2**2, 3**2)
z = x ** 2

# Simple comparison
z = x > 0       # Element-wise boolean comparison
z = x < 0

# Matrix multiplication
x1 = torch.rand((2, 5))
x2 = torch.rand((5, 3))

x3 = torch.mm(x1, x2) # output: 2x3 matrix
x3 = x1.mm(x2)

# Matrix exponentiation
matrix_exp = torch.rand(5, 5)
matrix_exp.matrix_power(3)  # Matrix multiply by itself 3 times

# Element-wise multiplication
z = x * y  # 1*9, 2*8, 3*7

# Dot product
z = torch.dot(x, y) # Sum of element-wise multiplication

# Batch matrix multiplication
batch = 32
n = 10
m = 20
p = 30

tensor1 = torch.rand((batch, n, m)) # 32 batches of 10 x 20 matrices

tensor2 = torch.rand((batch, m, p)) # 32 batches of 20 x 30 matrices

out_bmm = torch.bmm(tensor1, tensor2) # Matrix multiplication across the non-batch shapes that match (multiplies by the "m" dimension) Output: (batch, n, p)

# Example of Broadcasting
x1 = torch.rand((5, 5))
x2 = torch.rand((1, 5))

# can't subtract or raize a matrix by a vector. 
# Torch expands the first dimension of x2 to match x1
# Copies across all of the rows to get a 5x5 (all rows identical)

z = x1 - x2 
z = x1 ** x2

# Other useful tensor operations
# For a lot of these you can just use <var>.<function()> (e.x. x.max(dim=0))
sum_x = torch.sum(x, dim=0)
values, indices = torch.max(x, dim=0) # Max value and index of max (or x.max(dim=0))
values, indices = torch.min(x, dim=0)
abs_x = torch.abs(x)
z = torch.argmax(x, dim=0) # Only returns the index of the max, not the value
z = torch.argmin(x, dim=0)
mean_x = torch.mean(x.float(), dim=0) # pyTorch requires the input to .mean() to be a float
z = torch.eq(x, y) # True for indices where the elements that are the same between two tensors, False for elts that are different
sorted_y, indices = torch.sort(y, dim=0, descending=False) # returns the sorted tensor and the original indices of the elements that were sorted

z = torch.clamp(x, min=0, max=10) # Clamps all elements of x to a min of 0 and max of 10 (ReLU uses this)

x = torch.tensor([1,0,1,1,1], dtype=torch.bool)
z = torch.any(x) # Evaluate whether ANY elements of x are True
z = torch.all(x) # Evaluate whether ALL elements of x are True


---

## Tensor Indexing

In [ ]:
batch_size = 10
features = 25
x = torch.rand((batch_size, features))

# Get the features of the first example
print(x[0].shape) # x[0,:]

# Get the first feature of all examples
print(x[:, 0].shape)

# Get the first 10 features from the third example in the batch
print(x[2, 0:10]) # 0:10 -> [0, 1, 2, ..., 9]

# Can use slicing to assign values
x[0, 0] = 100

# Fancy indexing
x = torch.arange(10)
indices = [2, 5, 8]
print(x[indices]) # prints out only the values at the specified indices

x = torch.rand((3, 5))
rows = torch.tensor([1, 0])
cols = torch.tensor([4, 0])

print(x[rows, cols]) # picks out elements at [1,4] and [0,0]

# More advanced indexing
x = torch.arange(10)
print(x[(x < 2 ) | (x > 8)]) # Picks out elements less than 2 OR greater than 8 (Use '&' for AND)
print(x[x.remainder(2) == 0]) # Picks out elements that have a the modulus 2 == 0 (even numbers)

# Useful operations
print(torch.where(x > 5, x, x*2)) # For all elements where x > 5, return the value. Otherwise, multiply it by 2
print(torch.tensor([0,0,1,2,2,3,4]).unique())
print(x.ndimension()) # Return the number of dimensions in the tensor (5x5x5 would return 3)
print(x.numel()) # Return the number of elements in x (across all dimensions)

torch.Size([25])
torch.Size([10])
tensor([0.8657, 0.7053, 0.4653, 0.6917, 0.6900, 0.5571, 0.9293, 0.2241, 0.8780,
        0.8858])
tensor([2, 5, 8])
tensor([0.6912, 0.5966])
tensor([0, 1, 9])
tensor([0, 2, 4, 6, 8])
tensor([ 0,  2,  4,  6,  8, 10,  6,  7,  8,  9])
tensor([0, 1, 2, 3, 4])
1
10


---

## Tensor Reshaping

In [ ]:
x = torch.arange(9)

# View and reshape are very similar
# View acts on contiguous tensors (stored in contiguous memory)
# Reshape can work on non-contiguous tensors (makes a copy if non-contiguous, better to use view if possible)
x_3x3 = x.view(3, 3) # Re-arrange the tensor into 3 rows and 3 columns
x_3x3 = x.reshape(3,3)
print(x_3x3)

y = x_3x3.T # transpose (can also use .t())
print(y.contiguous().view(9)) # If you use reshape, it can make the tensor non-contiguous and will throw an error if you use view()

x1 = torch.rand((2, 5))
x2 = torch.rand((2, 5))

print(torch.cat((x1, x2), dim=0).shape) # Add the elements of one tensor to another across the specified dimension
print(torch.cat((x1, x2), dim=1).shape) 

z = x1.view(-1) # Flatten the last dimension
print(z.shape)

batch = 64
x = torch.rand((batch, 2, 5))
z = x.view(batch, -1) # Keeps the batch dimension, but collapses the 2x5 dimension to 10
print(z.shape)

# Switch the axis
z = x.permute(0, 2, 1) # Keep batch at 0, but put 5 at dimension 1 and 2 at dimension 2 (special transpose)
print(z.shape)

x = torch.arange(10) # [10]
print(x.unsqueeze(0).shape) # Add an empty dimension at 0
print(x.unsqueeze(1).shape)

# You can chain unsqueeze to add multiple empty dimensions
x = torch.arange(10).unsqueeze(0).unsqueeze(1) # 1x1x10
print(x.shape)

z = x.squeeze(1)
print(z.shape)


tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
tensor([0, 3, 6, 1, 4, 7, 2, 5, 8])
torch.Size([4, 5])
torch.Size([2, 10])
torch.Size([10])
torch.Size([64, 10])
torch.Size([64, 5, 2])
torch.Size([1, 10])
torch.Size([10, 1])
torch.Size([1, 1, 10])
tensor([[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]])
torch.Size([1, 10])
